version: 2.1
executors:
  android_executor: android/android

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android_executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          command: ./gradlew build
  check_code:
    executor: android_executor
    steps:
      - run:
          name: Run Linters
          command: sudo chmod +x ./gradlew lint
  unit_tests:
    executor: android_executor
    steps:
      - run:
          name: Run Tests
          command: sudo chmod +x ./gradlew test
  storage:
    executor: android_executor
    steps:
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

workflows:
  version: 2.1
  on_commit:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - check_code:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - unit_tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - storage:
          requires:
            - build
            - check_code
            - unit_tests
          filters:
            branches:
              ignore:
                - master
